name: product_development
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiohttp-retry=2.9.1
  - aiosignal=1.4.0
  - amqp=5.2.0
  - antlr-python-runtime=4.9.3
  - appdirs=1.4.4
  - arrow=1.4.0
  - astroid=3.3.11
  - asttokens=3.0.0
  - asyncssh=2.21.1
  - atpublic=7.0.0
  - attrs=25.4.0
  - backports.zoneinfo=0.2.1
  - billiard=4.2.3
  - binaryornot=0.4.4
  - blas=1.0
  - blinker=1.9.0
  - boto3=1.41.5
  - botocore=1.41.5
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.16.0
  - celery=5.4.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - chardet=5.2.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1.2
  - click-repl=0.3.0
  - colorama=0.4.6
  - comm=0.2.3
  - configobj=5.0.9
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cookiecutter-data-science=2.3.0
  - cycler=0.11.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - dictdiffer=0.9.0
  - dill=0.4.0
  - diskcache=5.6.3
  - distro=1.9.0
  - dpath=2.2.0
  - dulwich=0.24.10
  - dvc=3.64.0
  - dvc-data=3.16.12
  - dvc-http=2.32.0
  - dvc-objects=5.1.2
  - dvc-render=1.0.2
  - dvc-studio-client=0.22.0
  - dvc-task=0.40.2
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - feature_engine=1.9.3
  - filelock=3.20.0
  - flask=3.1.2
  - flatten-dict=0.4.2
  - flufl.lock=8.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - funcy=2.0
  - future=1.0.0
  - getopt-win32=0.1
  - gitdb=4.0.12
  - gitpython=3.1.45
  - grandalf=0.7
  - graphite2=1.3.14
  - graphviz=8.1.0
  - gto=1.8.0
  - gts=0.7.6
  - h2=4.3.0
  - harfbuzz=7.3.0
  - hpack=4.1.0
  - hydra-core=1.3.2
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=72.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - isort=6.1.0
  - iterative-telemetry=0.0.10
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.8
  - kombu=5.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgd=2.3.3
  - libgit2=1.9.1
  - libglib=2.84.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libintl=0.22.5
  - libpng=1.6.50
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxgboost=2.0.3
  - libzlib=1.3.1
  - loguru=0.7.3
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - multidict=6.6.3
  - nest-asyncio=1.6.0
  - networkx=3.6
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - omegaconf=2.3.0
  - openjpeg=2.5.2
  - openssl=3.6.0
  - orjson=3.11.4
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.50.14
  - parso=0.8.5
  - pathlib2=2.3.7.post1
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.1.2
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py-xgboost=2.0.3
  - pycparser=2.22
  - pydot=4.0.1
  - pygit2=1.18.2
  - pygments=2.19.2
  - pygtrie=2.5.0
  - pylint=3.3.8
  - pyopenssl=24.3.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-gssapi=1.10.1
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=311
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - s3transfer=0.15.0
  - scikit-learn=1.7.1
  - scipy=1.16.2
  - scmrepo=3.5.6
  - seaborn=0.13.2
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - shortuuid=1.0.13
  - shtab=1.8.0
  - six=1.17.0
  - smmap=5.0.2
  - sqlite=3.50.2
  - sqltrie=0.11.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tabulate=0.9.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tomlkit=0.13.3
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.4.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vine=5.1.0
  - voluptuous=0.15.2
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - xgboost=2.0.3
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.1
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zc.lockfile=4.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - alembic==1.17.2
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - cachetools==6.2.2
      - cloudpickle==3.1.2
      - cryptography==46.0.3
      - databricks-sdk==0.73.0
      - docker==7.1.0
      - fastapi==0.122.0
      - flask-cors==6.0.1
      - google-auth==2.43.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - h11==0.16.0
      - huey==2.5.4
      - mako==1.3.10
      - mlflow==3.6.0
      - mlflow-skinny==3.6.0
      - mlflow-tracing==3.6.0
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - rsa==4.9.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.4
      - starlette==0.50.0
      - typing-inspection==0.4.2
      - uvicorn==0.38.0
      - waitress==3.0.2
      - werkzeug==3.1.4
prefix: C:\Users\fjgon\miniconda3\envs\product_development
