name: product_development
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - arrow=1.4.0
  - astroid=3.3.11
  - asttokens=3.0.0
  - binaryornot=0.4.4
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - chardet=5.2.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cookiecutter-data-science=2.3.0
  - cycler=0.11.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - dill=0.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - feature_engine=1.9.3
  - fonttools=4.60.1
  - freetype=2.13.3
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=7.1.0
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - isort=6.1.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.50
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxgboost=2.0.3
  - libzlib=1.3.1
  - loguru=0.7.3
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openjpeg=2.5.2
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.1
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.2
  - pure_eval=0.2.3
  - py-xgboost=2.0.3
  - pycparser=2.22
  - pygments=2.19.2
  - pylint=3.3.8
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-dotenv=1.2.1
  - python-slugify=8.0.4
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - requests=2.32.5
  - rich=14.2.0
  - scikit-learn=1.7.1
  - scipy=1.16.2
  - seaborn=0.13.2
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - text-unidecode=1.3
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tomlkit=0.13.3
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.4.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - xgboost=2.0.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: C:\Users\fjgon\miniconda3\envs\product_development
